# Generated by Django 4.0.1 on 2022-01-08 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='address2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='start@domain.dj', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='full_name',
            field=models.CharField(default='startname', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='has_active_repairs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='has_active_shop_orders',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='postcode',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='user_auth_account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='email',
            field=models.EmailField(default='start@domain.dj', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='full_name',
            field=models.CharField(default='startname', max_length=100),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='overlord_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='shop_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='user_auth_account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='workshop_staff',
            field=models.BooleanField(default=False),
        ),
    ]
