# Generated by Django 4.0.1 on 2022-01-08 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_customer_address1_customer_address2_customer_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='full_name',
            new_name='username',
        ),
    ]
