# Generated by Django 4.0.1 on 2022-01-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_customer_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffmember',
            old_name='overlord_permission',
            new_name='admin_access_permission',
        ),
        migrations.AddField(
            model_name='customer',
            name='staff_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
