# Generated by Django 4.0b1 on 2022-01-11 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('profiles', '0013_alter_customer_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
