# Generated by Django 4.0b1 on 2022-01-12 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_alter_customer_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffmember',
            old_name='user_auth_account',
            new_name='username',
        ),
    ]
