# Generated by Django 4.0b1 on 2022-01-30 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0009_remove_shopitemimage_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(default='start@domain.dj', max_length=254, unique=True)),
                ('address1', models.CharField(blank=True, max_length=100, null=True)),
                ('address2', models.CharField(blank=True, max_length=100, null=True)),
                ('postcode', models.CharField(blank=True, max_length=40, null=True)),
                ('town_or_city', models.CharField(blank=True, max_length=40, null=True)),
                ('country', models.CharField(blank=True, max_length=40, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('order_total', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_completed', models.BooleanField(default=False)),
                ('paid_on', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ShopCustomerInvoice',
            fields=[
                ('baseinvoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='invoices.baseinvoice')),
            ],
            bases=('invoices.baseinvoice',),
        ),
        migrations.CreateModel(
            name='WorkshopCustomerInvoice',
            fields=[
                ('baseinvoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='invoices.baseinvoice')),
                ('payment_type', models.CharField(choices=[('DEP', 'Deposit'), ('EP', 'End Payment'), ('SPT', 'Single Payment Total'), ('SP', 'Supplementary Payment')], max_length=25)),
            ],
            bases=('invoices.baseinvoice',),
        ),
        migrations.CreateModel(
            name='ShopLineItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('line_item_total', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('shop_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.shopitems')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='line_items', to='invoices.shopcustomerinvoice')),
            ],
        ),
    ]
