# Generated by Django 4.0b1 on 2022-01-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_baseinvoice_paid_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinvoice',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
