# Generated by Django 4.0b1 on 2022-01-30 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repairs_restorals', '0011_serviceticket_has_invoice'),
        ('invoices', '0006_workshopcustomerinvoice_service_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopcustomerinvoice',
            name='service_ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='repairs_restorals.serviceticket'),
        ),
    ]
