# Generated by Django 4.0b1 on 2022-01-30 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_alter_workshopcustomerinvoice_service_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopcustomerinvoice',
            name='service_ticket',
        ),
    ]
