# Generated by Django 4.0.1 on 2022-02-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_workshopcustomerinvoice_service_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseinvoice',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
