# Generated by Django 4.0.1 on 2022-02-07 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_rename_user_auth_account_staffmember_username'),
        ('invoices', '0013_alter_workshopcustomerinvoice_service_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopcustomerinvoice',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='profiles.customer'),
            preserve_default=False,
        ),
    ]
