# Generated by Django 4.0.2 on 2022-02-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0016_alter_workshopcustomerinvoice_service_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinvoice',
            name='order_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='baseinvoice',
            name='order_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='baseinvoice',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
