# Generated by Django 4.0.2 on 2022-02-22 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0017_alter_baseinvoice_order_amount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopLineItems',
        ),
    ]
