# Generated by Django 4.0b1 on 2022-01-17 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shopitemphoto_shopitems_description_shopitems_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitemphoto',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopitemphoto',
            name='linked_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.shopitems'),
            preserve_default=False,
        ),
    ]
