# Generated by Django 4.0b1 on 2022-01-17 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shopitemphoto_image_shopitemphoto_linked_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopitemphoto',
            name='linked_item',
        ),
        migrations.AddField(
            model_name='shopitemphoto',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.shopitems'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shopitemphoto',
            name='image',
            field=models.ImageField(upload_to='shop/images'),
        ),
    ]
