# Generated by Django 4.0b1 on 2022-01-17 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_shopitemphoto_linked_item_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopItemPhoto',
            new_name='ShopItemImage',
        ),
    ]
