# Generated by Django 4.0b1 on 2022-01-17 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_shopitemimage_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopitemimage',
            name='caption',
        ),
    ]
