# Generated by Django 4.0b1 on 2022-01-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_shopitemimage_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitems',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
