# Generated by Django 4.0.1 on 2022-02-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_shopitems_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitemimage',
            name='is_primary_image',
            field=models.BooleanField(default=False),
        ),
    ]
